ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'GENERAL_MANAGER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'REGIONAL_MANAGER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'BRANCH_MANAGER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'HALL_MANAGER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'CUSTOMER_SERVICE';

ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "employeeId" TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS "User_companyId_employeeId_key" ON "User"("companyId", "employeeId");
CREATE INDEX IF NOT EXISTS "User_employeeId_idx" ON "User"("employeeId");
